//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESRI.ArcGIS.Client.Toolkit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESRI.ArcGIS.Client.Toolkit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File upload failed..
        /// </summary>
        internal static string AttachmentEditor_FileUploadFailed {
            get {
                return ResourceManager.GetString("AttachmentEditor_FileUploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} attribution..
        /// </summary>
        internal static string Attribution_Copyright {
            get {
                return ResourceManager.GetString("Attribution_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark .
        /// </summary>
        internal static string Bookmark_Name {
            get {
                return ResourceManager.GetString("Bookmark_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save bookmarks: .
        /// </summary>
        internal static string Bookmark_SaveFailed {
            get {
                return ResourceManager.GetString("Bookmark_SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string FeatureDataForm_CommitButtonContent {
            get {
                return ResourceManager.GetString("FeatureDataForm_CommitButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string FeatureDataForm_DeleteButtonContent {
            get {
                return ResourceManager.GetString("FeatureDataForm_DeleteButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot apply changes when &apos;FeatureDataForm&apos; is in read-only mode..
        /// </summary>
        internal static string FeatureDataForm_EditInReadOnlyModeNotAllowed {
            get {
                return ResourceManager.GetString("FeatureDataForm_EditInReadOnlyModeNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;FeatureDataGrid&apos; row collection is empty..
        /// </summary>
        internal static string FeatureDataGrid_CollectionIsEmpty {
            get {
                return ResourceManager.GetString("FeatureDataGrid_CollectionIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index &apos;{0}&apos; must be greater than or equal to 0 and less than {1}..
        /// </summary>
        internal static string FeatureDataGrid_IndexOutOfRange {
            get {
                return ResourceManager.GetString("FeatureDataGrid_IndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid object type for &apos;{0}&apos;..
        /// </summary>
        internal static string FeatureDataGrid_InvalidObjectTypeForKey {
            get {
                return ResourceManager.GetString("FeatureDataGrid_InvalidObjectTypeForKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rows must be of type &apos;{0}&apos; for the &apos;{1}&apos; attribute..
        /// </summary>
        internal static string FeatureDataGrid_MixedAttributeTypesNotAllowed {
            get {
                return ResourceManager.GetString("FeatureDataGrid_MixedAttributeTypesNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object is null or its type cannot be determined..
        /// </summary>
        internal static string FeatureDataGrid_ObjectIsNullOrInvalidType {
            get {
                return ResourceManager.GetString("FeatureDataGrid_ObjectIsNullOrInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update the row at index {0}..
        /// </summary>
        internal static string FeatureDataGrid_RowUpdateFailed {
            get {
                return ResourceManager.GetString("FeatureDataGrid_RowUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records ({0} out of {1} Selected).
        /// </summary>
        internal static string FeatureDataGrid_SelectedAndTotalRows {
            get {
                return ResourceManager.GetString("FeatureDataGrid_SelectedAndTotalRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field type &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string FieldDomain_FieldTypeNotSupported {
            get {
                return ResourceManager.GetString("FieldDomain_FieldTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template child &apos;bigMap&apos; cannot be found..
        /// </summary>
        internal static string MagnifyingGlass_BigMapNotFoundInTemplate {
            get {
                return ResourceManager.GetString("MagnifyingGlass_BigMapNotFoundInTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}%.
        /// </summary>
        internal static string ProgressBar_ProgressPercentage {
            get {
                return ResourceManager.GetString("ProgressBar_ProgressPercentage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A certificate is required to access {0} on {1}.
        /// </summary>
        internal static string SignInDialog_CertificateRequired {
            get {
                return ResourceManager.GetString("SignInDialog_CertificateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;StackCount&apos; cannot be less than one..
        /// </summary>
        internal static string TemplatePanel_StackCountLessThanOne {
            get {
                return ResourceManager.GetString("TemplatePanel_StackCountLessThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be between {0} and {1}..
        /// </summary>
        internal static string Validation_InvalidRangeDomain {
            get {
                return ResourceManager.GetString("Validation_InvalidRangeDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; must be a valid &apos;{1}&apos; value..
        /// </summary>
        internal static string Validation_InvalidType {
            get {
                return ResourceManager.GetString("Validation_InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value &apos;{0}&apos; is not a valid &apos;{1}&apos; type for field &apos;{2}&apos;..
        /// </summary>
        internal static string Validation_InvalidValue {
            get {
                return ResourceManager.GetString("Validation_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; cannot be empty..
        /// </summary>
        internal static string Validation_ValueCannotBeNull {
            get {
                return ResourceManager.GetString("Validation_ValueCannotBeNull", resourceCulture);
            }
        }
    }
}
